### PR TITLE
Generate @DefaultValue annotation for query parameters with default values

### PR DESCRIPTION
**Pull request by reallyinsane**
Add @DefaultValue to @QueryParam if set.

### CODE REVIEW

**Comment by jpbelang** [comment]
A pull request ?  With decent testing ?  I'm touched :-)

I have to merge it into the release branch.  I'm not a home, but it will be done in my WE coding session.

Thanks.

**Comment by reallyinsane** [comment]
Hi,
I would like to ask you something different about extending the raml-for-jax-rs process. Actually it is possible to define extensions on types, resources, methods and responses. For the properties _onXXXCreation_/_onXXXFinish_ only class names can be provided. Some of the extensions I would like to use additionalProperties would be needed. 

So instead of e.g.

`onResourceClassCreation?: string[]`
  
I think about something like

`onResourceClassCreation?: ExtensionType[]`

where ExtensionType has a pre-defined property className and allows additionalProperties as well.

I have in mind extensions regarding JSR-250. So I would like to mark resources/methods with a PermitAll, DenyAll and RolesAllowed extension. For the latter one I need to specify the roles as properties.

E.g.

```
/humanity:
    (ramltojaxrs.resources):
        onResourceClassCreation: 
            className: org.raml.jaxrs.generator.builders.extensions.jsr250.DenyAllExtension
    get:
        (ramltojaxrs.methods):
            onResourceMethodCreation: 
                className: org.raml.jaxrs.generator.builders.extensions.jsr250.RolesAllowedExtension
                roles: [RoleA, RoleB]
        queryParameters:
            type: string
        responses:
            200:
                body:
                    application/json:
                        type: string
```
Do you think this might be a good idea or am I missing a way to achieve this already? 

Best Regards,

Matthias

**Comment by jpbelang** [comment]
Could you look at the 3.0 branch to see if this can help you ?  we redid bits of the plugins...

**Comment by reallyinsane** [comment]
Hi,

it was really hard to find out how to use the plugins. There is one plugin using arguments. But I got it working. My requirement was to be able to dynamically add annotations with dynamic values and the new plugin mechanism matches this.
 If you like you can have a look at [raml-to-jaxrs-jsr-250-plugin](https://github.com/reallyinsane/raml-to-jaxrs-jsr-250-plugin) which provides a plugin to generate JSR-250 annotations (`@DenyAll`, `@PermitAll`, `@RolesAllowed`) for resources and resource methods.

Looking forward for the release of 3.0.0

**Comment by jpbelang** [comment]
I actually saw something in your plugin that seems wrong.  Plugin methods, when you return null, should suppress the class generation.  Should you not want to affect generation, you should return the builder passed as an argument:
```java

  @Override
  public TypeSpec.Builder onResponseClass(ResourceContext context, GMethod method, TypeSpec.Builder typeSpec) {
    return typeSpec;
  }

  @Override
  public MethodSpec.Builder onMethod(ResourceContext context, GResponse responseMethod, MethodSpec.Builder methodSpec) {
    return methodSpec;
  }
```

**Comment by reallyinsane** [comment]
Thank you, I changed the behaviour and also updated the documentation.

**Pull request merged**
